apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-conf
  namespace: {{ .Values.namespace }}
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
        CertFile = "/ssl/tls.crt"
        KeyFile = "/ssl/tls.key"
    [acme]
    email = "{{ .Values.acme.email }}"
    storage = "traefik/acme/account"
    entryPoint = "https"
    onHostRule = true
    onDemand = true
    {{- if .Values.acme.staging }}
    caServer = "https://acme-staging.api.letsencrypt.org/directory"
    {{- end }}
    {{- if .Values.consul.enabled }}
    [consul]
    endpoint = "{{ .Values.consul.endpoint }}"
    watch = {{ .Values.consul.watch }}
    prefix = "{{ .Values.consul.prefix }}"
    {{- end }}
