apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "name" . }}
spec:
  replicas: {{ default 1 .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - image: {{ .Values.image }}:{{ .Values.imageTag }}
        name: {{ template "name" . }}
        volumeMounts:
        - mountPath: /config
          name: config
        {{- if .Values.ssl.enabled }}
        - mountPath: /ssl
          name: ssl
        {{- end }}
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
        - --kubernetes
        - --web
        - --acme.entryPoint="https"
        - --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
        - --entryPoints='Name:https Address::443 TLS'
        {{- if .Values.consul.enabled }}
        - --consul
        - --consul.endpoint={{ .Values.consul.endpoint }}
        - --consul.watch=true
        {{- else }}
        - --configfile=/config/traefik.toml
	{{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "name" . }}-conf
      {{- if .Values.ssl.enabled }}
      - name: ssl
        secret:
          secretName: {{ template "name" . }}-cert
      {{- end }}
