apiVersion: v1
kind: Service
metadata:
  name: traefik-webui
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if .Values.servicewebui }}
  {{- range $key, $value := .Values.servicewebui.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  selector:
    app: {{ template "name" . }}
  ports:
  - port: 8080
    targetPort: 8080
