apiVersion: v1
kind: Service
metadata:
  name: "{{ template "name" . }}"
  namespace: {{ .Values.namespace }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
    app: {{ template "name" . }}
spec:
  ports:
  - name: http
    port: {{.Values.HttpPort}}
  - name: rpc
    port: {{.Values.RpcPort}}
  - name: serflan-tcp
    protocol: "TCP"
    port: {{.Values.SerflanPort}}
  - name: serfwan-tcp
    protocol: "TCP"
    port: {{.Values.SerfwanPort}}
  - name: server
    port: {{.Values.ServerPort}}
  - name: consuldns
    port: {{.Values.ConsulDnsPort}}
  clusterIP: None
  selector:
    app: {{ template "name" . }}
---
